### ISSUE TITLE
AddBuiltinServices coredump

### ISSUE THREAD

**Issue by yjhjstz** [brpc/brpc#350]
```
(gdb) bt
#0  0x00007f3760eed604 in google::protobuf::Descriptor::full_name (this=0x0) at ./google/protobuf/descriptor.h:1836
#1  0x00007f3760ef7271 in google::protobuf::FieldDescriptor::FieldTypeNameDebugString (this=0x247c098)
    at google/protobuf/descriptor.cc:2640
#2  0x00007f3760ef7469 in google::protobuf::FieldDescriptor::DebugString (this=0x181fc18, depth=1,
    print_label_flag=google::protobuf::FieldDescriptor::PRINT_LABEL, contents=0x7ffd878b0e70, debug_string_options=...)
    at google/protobuf/descriptor.cc:2661
#3  0x00007f3760ef609e in google::protobuf::Descriptor::DebugString (this=0x2267590, depth=1, contents=0x7ffd878b0e70,
    debug_string_options=..., include_opening_clause=true) at google/protobuf/descriptor.cc:2557
#4  0x00007f3760ef5b7e in google::protobuf::Descriptor::DebugStringWithOptions (this=0x2267590, options=...)
    at google/protobuf/descriptor.cc:2504
#5  0x00007f3760ef5b37 in google::protobuf::Descriptor::DebugString (this=0x2267590) at google/protobuf/descriptor.cc:2498
#6  0x00007f37624c583a in brpc::ProtobufsService::Init (this=this@entry=0x226a000)
    at /home/luban/DDL-Serving/brpc/src/brpc/builtin/protobufs_service.cpp:54
#7  0x00007f37624c5f78 in brpc::ProtobufsService::ProtobufsService (this=0x226a000, server=<optimized out>)
    at /home/luban/DDL-Serving/brpc/src/brpc/builtin/protobufs_service.cpp:29
#8  0x00007f376249dbc4 in brpc::Server::AddBuiltinServices (this=this@entry=0x7ffd878b1680)
    at /home/luban/DDL-Serving/brpc/src/brpc/server.cpp:463
#9  0x00007f376249f966 in brpc::Server::StartInternal (this=0x7ffd878b1680, ip=..., port_range=..., opt=<optimized out>)
    at /home/luban/DDL-Serving/brpc/src/brpc/server.cpp:832
#10 0x00007f37624a01b0 in brpc::Server::Start (this=<optimized out>, endpoint=..., opt=<optimized out>)
    at /home/luban/DDL-Serving/brpc/src/brpc/server.cpp:992
#11 0x00007f37624a02da in brpc::Server::Start (this=<optimized out>, port=8002, opt=<optimized out>)
    at /home/luban/DDL-Serving/brpc/src/brpc/server.cpp:1010
#12 0x0000000000407073 in main (argc=1, argv=0x7ffd878b2490) at /home/luban/DDL-Serving/server.cc:170
```
* proto *
```c++
syntax = "proto2";

package caffe2;
import "caffe2/proto/caffe2.proto";

option cc_generic_services = true;

// Metadata for an inference request such as the model name and version.
message ModelSpec {
  // Required servable name.
  required string name = 1;

  // Optional version.
  optional int64 version = 2;

  // A named signature to evaluate. If unspecified, the default signature will
  // be used.
  optional string signature_name = 3;
}


message PredictRequest {
  // Model Specification. If version is not specified, will use the latest
  // (numerical) version.
  required ModelSpec model_spec = 1;

  // Input tensors.
  // Names of input tensor are alias names. The mapping from aliases to real
  // input tensor names is stored in the SavedModel export as a prediction
  // SignatureDef under the 'inputs' field.
  map<string, TensorProto> inputs = 2;
}

// Response for PredictRequest on successful run.
message PredictResponse {
   optional ModelSpec model_spec = 2;
  // Output tensors.
   map<string, TensorProto> outputs = 1;
}

// open source marker; do not remove
// PredictionService provides access to machine-learned models loaded by
// model_servers.
service PredictionService {
  rpc Predict(PredictRequest) returns (PredictResponse);
  
}
```

环境：
- Linux Centos
- gcc 4.8
- protobuf 3.5

@jamesge

**Comment by jamesge** [comment]
两种可能：pb 3.5内部bug（合理调用DebugString最终出现了this=0x0)，或链接库和头文件不符，比如头文件用了老版本pb生成的pb.h之类的。先试试从干净的repo从头编译

**Comment by yjhjstz** [comment]
注释掉 map 字段，编译启动就没这个问题了，能否绕过去呢？
