### ISSUE TITLE
gcc 4.8.5 局部静态std::string 的访问是否存在线程安全问题？

### ISSUE THREAD

**Issue by eddie74748** [brpc/brpc#368]
brpc中使用了一个局部静态变量字符串，
[https://github.com/brpc/brpc/blob/master/src/brpc/span.cpp](url) line no. 141
这样相当于多线程访问一个全局的std::string， 是否本身就不可取？

1. 

遇到如下core，并且并发一高便很容易重现，调用堆栈：
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd37fe700 (LWP 25242)]
0x00007ffff70291f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install gflags-2.1.1-6.el7.x86_64 glibc-2.17-196.el7_4.2.x86_64 gperftools-libs-2.4-8.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 leveldb-1.12.0-11.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libgcc-4.8.5-16.el7_4.2.x86_64 libselinux-2.5-11.el7.x86_64 libstdc++-4.8.5-16.el7_4.2.x86_64 libunwind-1.2-2.el7.x86_64 libuuid-2.23.2-33.el7.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-17.el7.x86_64 protobuf-2.5.0-8.el7.x86_64 protobuf-compiler-2.5.0-8.el7.x86_64 snappy-1.1.0-3.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007ffff70291f7 in raise () from /lib64/libc.so.6
#1  0x00007ffff702a8e8 in abort () from /lib64/libc.so.6
#2  0x00007ffff792fac5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007ffff792da36 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff792da63 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff792dc83 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007ffff792e21d in operator new(unsigned long) () from /lib64/libstdc++.so.6
#7  0x00007ffff798ccf9 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()
   from /lib64/libstdc++.so.6
#8  0x00007ffff798d90b in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) () from /lib64/libstdc++.so.6
#9  0x00007ffff798dfdc in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)
    () from /lib64/libstdc++.so.6
#10 0x00007ffff3e57704 in unknown_span_name () at /usr/local/src/game_service/trunk/brpc/src/brpc/span.cpp:144
#11 brpc::Span::CreateServerSpan (trace_id=2035823792, span_id=0, parent_span_id=0, base_real_us=1527748486177590)
    at /usr/local/src/game_service/trunk/brpc/src/brpc/span.cpp:187
#12 0x00007ffff3dca86c in brpc::policy::ProcessSnailRpcRequest (msg_base=0x7fffc805f890)
    at /usr/local/src/game_service/trunk/brpc/src/brpc/policy/snail_rpc_protocol.cpp:382
#13 0x00007ffff3e6df7a in brpc::ProcessInputMessage (void_arg=<optimized out>)
    at /usr/local/src/game_service/trunk/brpc/src/brpc/input_messenger.cpp:132
#14 0x00007ffff3d2ceea in bthread::TaskGroup::task_runner (skip_remained=<optimized out>)
    at /usr/local/src/game_service/trunk/brpc/src/bthread/task_group.cpp:297
#15 0x00007ffff3d307e1 in bthread_make_fcontext () from libbrpc.so
#16 0x0000000000000000 in ?? ()
(gdb) f 10
#10 0x00007ffff3e57704 in unknown_span_name () at /usr/local/src/game_service/trunk/brpc/src/brpc/span.cpp:144
144	/usr/local/src/game_service/trunk/brpc/src/brpc/span.cpp: No such file or directory.
(gdb) p s_unknown_method_name._M_dataplus._M_p
$1 = 0x7fffa0041838 "unknown_method"
(gdb) x/64 0x7fffa0041820
0x7fffa0041820:	-1610027392	32767	14	0
0x7fffa0041830:	-1	0	1852534389	1601075055
0x7fffa0041840:	1752458605	25711	149	0
0x7fffa0041850:	67	0	110	0
0x7fffa0041860:	1	0	1600352370	1987208563
0x7fffa0041870:	861893221	1597059126	1634493810	1852795252
0x7fffa0041880:	1919251295	1701013878	1952802655	1634493023
0x7fffa0041890:	1818192739	1601467241	1702125932	1601790830
0x7fffa00418a0:	1668441456	1769238117	7562604	0
0x7fffa00418b0:	0	0	0	0
0x7fffa00418c0:	0	0	0	0
0x7fffa00418d0:	0	0	5733	0
0x7fffa00418e0:	-198089360	32767	-1610346184	32767
0x7fffa00418f0:	-1610338344	32767	1	0
0x7fffa0041900:	0	0	0	0
0x7fffa0041910:	0	0	0	0
```
core的原因是发现s_unknown_method_name这个对象已经被析构 
(查看内存可以发现std::string内部成员已被写坏)
```
struct _Rep_base
      {
	size_type		_M_length;   // 0x7fffa0041820:
	size_type		_M_capacity;
	_Atomic_word		_M_refcount; // -1
      };
```

2 . 

gcc 4.8.5下，std::string仍然使用了共享内存和引用计数（glibc++实现确实使用了原子操作来保证refcout线程安全），但是当我使用gdb调试watch以上静态字符串s_unknown_method_name的reftcout内存数据时，发现refcout值变化异常：
```
[Switching to Thread 0x7f6e87fff700 (LWP 24549)]
Hardware watchpoint 2: *(int*)0x7f6ea805b620

Old value = 1
New value = 4
0x00007f6ec6899ffb in std::basic_string, std::allocator >::basic_string(std::string const&) ()
   from /lib64/libstdc++.so.6
(gdb) bt
#0  0x00007f6ec6899ffb in std::basic_string, std::allocator >::basic_string(std::string const&) ()
   from /lib64/libstdc++.so.6
#1  0x00007f6ec2fe3704 in unknown_span_name () at /usr/local/src/game_service/trunk/brpc/src/brpc/span.cpp:144
#2  brpc::Span::CreateServerSpan (trace_id=2035823792, span_id=0, parent_span_id=0, base_real_us=1527748486177589)
    at /usr/local/src/game_service/trunk/brpc/src/brpc/span.cpp:187
#3  0x00007f6ec2f5686c in brpc::policy::ProcessSnailRpcRequest (msg_base=0x7f6e60028460)
    at /usr/local/src/game_service/trunk/brpc/src/brpc/policy/snail_rpc_protocol.cpp:382
#4  0x00007f6ec2ff9f7a in brpc::ProcessInputMessage (void_arg=)
    at /usr/local/src/game_service/trunk/brpc/src/brpc/input_messenger.cpp:132
#5  0x00007f6ec2eb8eea in bthread::TaskGroup::task_runner (skip_remained=)
    at /usr/local/src/game_service/trunk/brpc/src/bthread/task_group.cpp:297
#6  0x00007f6ec2ebc7e1 in bthread_make_fcontext () from libbrpc.so
#7  0x0000000000000000 in ?? ()
```

refcout值从1变成4，是否可以认为，std::string的引用计数不是 thread-safe的？

3 . 

并且当我把static string改成如下常量字符串，问题便无法再重现。。。
```
inline const std::string unknown_span_name() {
    // thread-safe in gcc.
    // static std::string s_unknown_method_name = "unknown_method";
    // return s_unknown_method_name;
    return "unknown_method";
}
```

**Comment by jamesge** [comment]
C++11中的static初始化是线程安全的，这里的问题要么是发生在main函数之后（某个线程中），要么是相关内存被写坏了，可以跑下address sanitizer

**Comment by lip23** [comment]
请问你这个问题最后怎么解决的，我也遇到了相同的问题。

**Comment by eddie74748** [comment]
我这边最后发现是依赖了一个没有用c++11编译的外部库




| |
刘涛
邮箱：liutao74748@163.com
|

签名由 网易邮箱大师 定制

在2019年01月28日 09:19，lipcat 写道：

请问你这个问题最后怎么解决的，我也遇到了相同的问题。
