### ISSUE TITLE
局部静态变量初始化抛异常

### ISSUE THREAD

**Issue by eddie74748** [brpc/brpc#384]
brpc服务启动时有几率产生如下core dump

```
Program terminated with signal 6, Aborted.
#0  0x00007fa8e03e2277 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-11.el7.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 libuuid-2.23.2-52.el7.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007fa8e03e2277 in raise () from /lib64/libc.so.6
#1  0x00007fa8e03e3968 in abort () from /lib64/libc.so.6
#2  0x00007fa8e0cf19d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007fa8e0cef946 in ?? () from /lib64/libstdc++.so.6
#4  0x00007fa8e0cee909 in ?? () from /lib64/libstdc++.so.6
#5  0x00007fa8e0cef574 in __gxx_personality_v0 () from /lib64/libstdc++.so.6
#6  0x00007fa8e0788903 in ?? () from /lib64/libgcc_s.so.1
#7  0x00007fa8e0788c9b in _Unwind_RaiseException () from /lib64/libgcc_s.so.1
#8  0x00007fa8e0cefb86 in __cxa_throw () from /lib64/libstdc++.so.6
#9  0x00007fa8e0cefe30 in __cxa_guard_acquire () from /lib64/libstdc++.so.6
#10 0x00007fa8de574e08 in bthread::allocate_stack_storage (s=0x7fa8cc018ef0, stacksize_in=1048576, guardsize_in=4096)
    at /xg_brpc/src/bthread/stack.cpp:54
#11 0x00007fa8de56a55c in Wrapper (entry=0x7fa8de568200 <bthread::TaskGroup::task_runner(long)>, this=<optimized out>)
    at /xg_brpc/src/bthread/stack_inl.h:50
#12 get<void (*)(long)> (a1=<synthetic pointer>, this=0x7fa8cc018c90) at /xg_brpc/src/butil/object_pool_inl.h:188
#13 get_object<void (*)(long)> (arg1=<synthetic pointer>, this=<optimized out>)
    at /xg_brpc/src/butil/object_pool_inl.h:235
#14 get_object<bthread::StackFactory<bthread::NormalStackClass>::Wrapper, void (*)(long)> (arg1=<synthetic pointer>)
    at /xg_brpc/src/butil/object_pool.h:78
#15 get_stack (entry=0x7fa8de568200 <bthread::TaskGroup::task_runner(long)>) at /xg_brpc/src/bthread/stack_inl.h:68
#16 bthread::get_stack (type=<optimized out>, entry=0x7fa8de568200 <bthread::TaskGroup::task_runner(long)>)
    at /xg_brpc/src/bthread/stack_inl.h:100
#17 0x00007fa8de56877f in sched_to (next_tid=<optimized out>, pg=0x7fa8dac28df0)
    at /xg_brpc/src/bthread/task_group_inl.h:62
#18 bthread::TaskGroup::run_main_task (this=0x7fa8cc0008c0) at /xg_brpc/src/bthread/task_group.cpp:147
#19 0x00007fa8de55e42e in bthread::TaskControl::worker_thread (arg=0x1ae8c50)
    at /xg_brpc/src/bthread/task_control.cpp:73
#20 0x00007fa8dfcfbe25 in start_thread () from /lib64/libpthread.so.0
#21 0x00007fa8e04aabad in clone () from /lib64/libc.so.6
(gdb)
```

gcc版本为4.8.5 

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

栈帧可以看到大概是因为gcc为局部静态变量的初始化添加的锁，
并且运行时检测到线程重入了该静态变量的初始化，从而引发异常。

请问：
1. gcc的版本是否有要求；

2. 类似问题是否有排查方向；

**Comment by jamesge** [comment]
#368 报过一个类似的问题。这个问题是比较奇怪，建议还是先跑下asan, gcc 4.8已经集成了
