### ISSUE TITLE
brpc能支持protobuf3的map类型

### ISSUE THREAD

**Issue by qqsun8819** [brpc/brpc#600]
**问题描述**
之前的项目中是grpc，一些Proto文件是proto3语法，并使用了map，在使用brpc替换grpc接入时，用map描述的结构在使用时会挂掉，比如调用 ShortDebugString时core在下面：
```
#0  0x00007f1d4962f280 in google::protobuf::FieldDescriptor::is_map() const ()
   from /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#1  0x00007f1d496891e0 in google::protobuf::internal::GeneratedMessageReflection::FieldSize(google::protobuf::Message const&, google::protobuf::FieldDescriptor const*) const () from /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#2  0x00007f1d49689edd in google::protobuf::internal::GeneratedMessageReflection::ListFields(google::protobuf::Message const&, std::vector<google::protobuf::FieldDescriptor const*, std::allocator<google::protobuf::FieldDescriptor const*> >*) const ()
   from /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x00007f1d496c8818 in google::protobuf::TextFormat::Printer::Print(google::protobuf::Message const&, google::protobuf::TextFormat::Printer::TextGenerator*) const () from /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x00007f1d496c89fc in google::protobuf::TextFormat::Printer::Print(google::protobuf::Message const&, google::protobuf::io::ZeroCopyOutputStream*) const
    () from /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#5  0x00007f1d496c8a8e in google::protobuf::TextFormat::Printer::PrintToString(google::protobuf::Message const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const () from /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007f1d496c8c0a in google::protobuf::Message::ShortDebugString[abi:cxx11]() const ()
   from /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```

**Feature描述**
想请教一下 brpc内部实现中，是哪个地方对类型做了限制，大概需要怎么改可以让brpc支持map这个类型，我们可以在内部先改一下，如果能搞定，我可以提一个PR出来

**Comment by jamesge** [comment]
这里没有限制，并且pb 2.x中的repeated message是和map二进制兼容的。这里的coredump可能是其他原因。

**Comment by qqsun8819** [comment]
谢谢 @jamesge 的回复 。我在做的事情是把brpc做为一个新的protocol接入tensorflow，目前tensorflow的so里面打入了grpc，我把brpc打进去以后 ，我怀疑是哪里起了冲突，因为把brpc的库链接进去以后 grpc也跑不过会出一样的core，而把brpc的库从tf的so中链接去掉，就没问题。你有没有什么提示呢，比如pb 哪里有什么 全局的东西 会导致此类问题

**Comment by chenzhangyi** [comment]
这个是因为_pywrap_tensorflow_internal(由于依赖了brpc)引入了protobuf的符号，和tensorflow_framework.so里面有符号冲突， 这个需要brpc里面都依赖protobuf_headers, 你可以先打一个bazel patch来解决这个问题.

**Comment by qqsun8819** [comment]
@chenzhangyi  谢谢回复 ，原因 找到了，是mcpack 中链接的protoc_lib 与grpc中的冲突，改此为probobuf_headers后问题解决了。目前是通过对bazel上打一个patch来解决 ，你觉得 有没有可能加一个select条件来控制这个，这样brpc以bazel形式加入其它项目 的时候 就可以通过配置来解决 ，如果你觉得 可行， 我可以提一个PR
